{{- if .Values.ingresses }}
{{- $root := . }}
{{- range $name, $ingress := .Values.ingresses }}
{{- if not $ingress.disabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
{{- if $ingress.annotations }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{- if $ingress.customLabels }}
{{ toYaml $ingress.customLabels | indent 4 }}
{{- else }}
{{ include "voice-chart.labels" $root | indent 4 }}
{{- end }}
{{- if $ingress.app }}
    app: "{{ $ingress.app }}"
{{- else }}
    app: {{ $name }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
{{ toYaml $ingress.rules | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
