{{- if .Values.statefulsets }}
{{- $root := . }}
{{- range $name, $statefulset := .Values.statefulsets }}
{{- if not $statefulset.disabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
{{- if $statefulset.annotations }}
  annotations:
{{ toYaml $statefulset.annotations | indent 4 }}
{{- end }}
  labels:
{{- if $statefulset.customLabels }}
{{ toYaml $statefulset.customLabels | indent 4 }}
{{- else }}
{{ include "voice-chart.labels" $root | indent 4 }}
    app: {{ $name }}
{{- end }}
spec:
  replicas: {{ $statefulset.replicaCount }}
{{- if $statefulset.serviceName }}
  serviceName: {{ $statefulset.serviceName }}
{{- end }}
{{- if $statefulset.updateStrategy }}
  updateStrategy:
{{ toYaml $statefulset.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
{{- if $statefulset.customSelectors }}
{{ toYaml $statefulset.customSelectors | indent 6 }}
{{- else }}
      app: {{ $name }}
{{- end }}
  template:
    metadata:
{{- if $statefulset.podAnnotations }}
      annotations:
{{ toYaml $statefulset.podAnnotations | indent 8 }}
{{- end }}
      labels:
{{- if $statefulset.customLabels }}
{{ toYaml $statefulset.customLabels | indent 8 }}
{{- else }}
{{ include "voice-chart.labels" $root | indent 8 }}
        app: {{ $name }}
{{- end }}
    spec:
{{- if $statefulset.sa }}
      serviceAccountName: {{ $statefulset.sa }}
{{- end }}
{{- if $statefulset.nodeSelectors }}
      nodeSelector:
{{- range $key, $val := $statefulset.nodeSelectors }}
        {{ $key }}: {{ $val | quote }}
{{- end}}
{{- end }}
{{- if $statefulset.volumes }}
      volumes:
{{ toYaml $statefulset.volumes | indent 6 }}
{{- end }}

{{- if $statefulset.initContainers }}
      initContainers:
{{- end }}
{{- range $name, $init := $statefulset.initContainers }}
      - name: "{{ if $init.name }}{{ $init.name }}{{ else }}{{ $name }}{{ end }}"
        image: "{{ tpl $init.image $ }}"
        imagePullPolicy: "{{ if $init.imagePullPolicy }}{{ $init.imagePullPolicy }}{{ else }}Always{{ end }}"
{{- if $init.command }}
        command:
{{ tpl (toYaml $init.command) $ | indent 8 }}
{{- end }}
{{- if $init.args }}
        args:
{{ tpl (toYaml $init.args) $ | indent 8 }}
{{- end }}
{{- if $init.volumeMounts }}
        volumeMounts:
{{ toYaml $init.volumeMounts | indent 8 }}
{{- end }}
{{- if $init.securityContext }}
        securityContext:
{{ toYaml $init.securityContext | indent 10 }}
{{- end }}
{{- if or $init.extraVars $init.secretKeyRef }}
        env:
{{- end }}
{{- if $init.extraVars }}
{{- range $key, $val := $init.extraVars }}
        - name: {{ $key | quote }}
          value: {{ tpl $val $ | quote }}
{{- end }}
{{- end }}
{{- if $init.secretKeyRef }}
{{ toYaml $init.secretKeyRef | indent 8 }}
{{- end }}
{{- if $init.resources }}
        resources:
{{ toYaml $init.resources | indent 10 }}
{{- end }}
{{- end }}
      containers:
{{- range $name, $container := $statefulset.containers }}
      - name: {{ $name }}
        image: "{{ tpl $container.image $ }}"
        imagePullPolicy: "{{ if $container.imagePullPolicy }}{{ $container.imagePullPolicy }}{{ else }}Always{{ end }}"
{{- if $container.command }}
        command:
{{ tpl (toYaml $container.command) $ | indent 8 }}
{{- end }}
{{- if $container.args }}
        args:
{{ tpl (toYaml $container.args) $ | indent 8 }}
{{- end }}
{{- if $container.containerPorts }}
        ports:
{{ toYaml $container.containerPorts | indent 8 }}
{{- end }}
{{- if $container.volumeMounts }}
        volumeMounts:
{{ toYaml $container.volumeMounts | indent 8 }}
{{- end }}
{{- if $container.securityContext }}
        securityContext:
{{ toYaml $container.securityContext | indent 10 }}
{{- end }}
{{- if $container.extraVars }}
        env:
{{- range $key, $val := $container.extraVars }}
        - name: {{ $key | quote }}
          value: {{ tpl $val $ | quote }}
{{- end}}
{{- end }}
{{- if $container.lifecycle }}
        lifecycle:
{{ toYaml $container.lifecycle | indent 10 }}
{{- end }}
{{- if $container.livenessProbe }}
        livenessProbe:
{{ toYaml $container.livenessProbe | indent 10 }}
{{- end }}
{{- if $container.readinessProbe }}
        readinessProbe:
{{ toYaml $container.readinessProbe | indent 10 }}
{{- end }}
{{- if $container.startupProbe }}
        startupProbe:
{{ toYaml $container.startupProbe | indent 10 }}
{{- end }}
{{- if $container.resources }}
        resources:
{{ toYaml $container.resources | indent 10 }}
{{- end }}
{{- end }}
{{- if $statefulset.affinity }}
      affinity:
{{ toYaml $statefulset.affinity | indent 8 }}
{{- end }}
{{- if $statefulset.tolerations }}
      tolerations:
{{ toYaml $statefulset.tolerations | indent 6 }}
{{- end }}
{{- if $statefulset.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $statefulset.terminationGracePeriodSeconds }}
{{- end }}
{{- if $statefulset.volumeClaimTemplates }}
  volumeClaimTemplates:
{{ toYaml $statefulset.volumeClaimTemplates | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
