defaults:
  agents: &default-agents
    queue: voice-app-builder-v2
  plugins: &default-plugins
    - first-aml/git-clone:
        repository: https://github.com/voice-social/voice-buildkite-template.git

steps:

# build docker images
  - label: ":docker: trigger docker build hyperion-history-api"
    command:
      - "buildkite-agent pipeline upload voice-buildkite-template/docker/build/template.yaml"
    env:
      IMAGE: gcr.io/voice-dev-infra-services/voice/voice-eos-hyperion
      TAG: ${BUILDKITE_COMMIT}
      DOCKERFILE: Dockerfile
      BUILDKITE_AGENT: voice-app-builder-v2
    agents: *default-agents
    plugins: *default-plugins
    if: build.tag == null

  - wait

# dev deploy
  - label: ":buildkite: Upload dev deploy pipeline"
    command: |
      buildkite-agent meta-data set K8S_NAMESPACE "dev"
      buildkite-agent pipeline upload .buildkite/dev.yaml
    agents:
      queue: voice-infra-devel-v2
    if: build.tag == null && build.branch == "voice-main" && build.pull_request.id == null
    retry:
      manual:
        permit_on_passed: true

  - wait

# promote image
  - label: ":docker: trigger docker promote image"
    command:
      - "buildkite-agent pipeline upload voice-buildkite-template/docker/promote/template.yaml"
    env:
      BASE_IMAGE: gcr.io/voice-dev-infra-services/voice/voice-eos-hyperion:${BUILDKITE_COMMIT}
      TARGET_IMAGE: gcr.io/voice-prod-infra-services/voice/voice-eos-hyperion:${BUILDKITE_COMMIT}
      BUILDKITE_AGENT: voice-app-builder-v2
    agents: *default-agents
    plugins: *default-plugins
    if: build.tag == null && build.branch == "voice-main" && build.pull_request.id == null

  - wait

# prod deploy
  - label: ":buildkite: Upload prod deploy pipeline"
    command: |
      buildkite-agent pipeline upload .buildkite/prod.yaml
    agents:
      queue: voice-infra-prod-v2
    if: build.tag == null && build.branch == "voice-main" && build.pull_request.id == null
    retry:
      manual:
        permit_on_passed: true
