defaults:
  agents: &default-agents
    queue: voice-app-builder-v2
  plugins: &default-plugins
    - first-aml/git-clone:
        repository: https://github.com/voice-social/voice-buildkite-template.git

steps:
# build docker images dev-main
  - label: ":building_construction: Trigger kaniko build"
    command:
      - "buildkite-agent pipeline upload voice-buildkite-template/kaniko/build/template.yaml"
    env:
      IMAGE: gcr.io/voice-dev-infra-services/voice/voice-eos-hyperion
      DOCKERFILE: Dockerfile
    agents: *default-agents
    plugins: *default-plugins
    if: build.tag == null

  - wait

# dev deploy
  - label: ":buildkite: Upload dev deploy pipeline"
    command: |
      buildkite-agent pipeline upload .buildkite/dev.yaml
    agents:
      queue: voice-main-dev-deployer
    if: build.tag == null && build.branch == "master" && build.pull_request.id == null
    retry:
      manual:
        permit_on_passed: true

  - wait
  - block: ":rocket: Release!"
    if: build.tag == null && build.branch == "master" && build.pull_request.id == null
# promote image
  - label: ":arrow_up: Trigger gcrane promote"
    command:
      - "buildkite-agent pipeline upload voice-buildkite-template/gcrane/promote/template.yaml"
    env:
      IMAGE_NAME: voice-eos-hyperion
    agents: *default-agents
    plugins: *default-plugins
    if: build.tag == null && build.branch == "master" && build.pull_request.id == null

  - wait

# prod deploy
  - label: ":buildkite: Upload prod deploy pipeline"
    command: |
      buildkite-agent pipeline upload .buildkite/prod.yaml
    agents:
      queue: voice-infra-prod-v2
    if: build.tag == null && build.branch == "master" && build.pull_request.id == null
    retry:
      manual:
        permit_on_passed: true
