defaults:
  agents: &default-agents
    queue: voice-app-builder-v2

steps:
# helm deploy to prod
  - label: ":helm: Trigger Helm Deploy"
    command: |
      export NO_PROXY="\${KUBERNETES_SERVICE_HOST}"
      echo "--- :helm: Helm dry-run"
      if helm upgrade -i $${HELM_RELEASE} helm/ -f $${HELM_VALUE_FILE} -n $${HELM_RELEASE_NAMESPACE} --set release.tag=$${HELM_RELEASE_TAG} --dry-run > /dev/null; then
        echo "dry-run completed OK."
      else
        exit 1;
      fi
      echo "--- :helm: Helm deploy"
      helm upgrade -i ${HELM_RELEASE} helm/ -f ${HELM_VALUE_FILE} -n ${HELM_RELEASE_NAMESPACE} --set release.tag=${HELM_RELEASE_TAG} 
    env:
      HELM_RELEASE: voice-payments-graphql
      HELM_RELEASE_NAMESPACE: prod
      HELM_RELEASE_TAG: ${BUILDKITE_COMMIT}
      HELM_VALUE_FILE: helm/values/prod.yaml
      BUILDKITE_AGENT: voice-infra-prod-v2
    concurrency: 1
    concurrency_group: "${BUILDKITE_PIPELINE_SLUG}/prod"
    agents: *default-agents
