defaults:
  agents: &default-agents
    queue: voice-main-prod-deployer
  plugins: &default-plugins
    - first-aml/git-clone:
        repository: https://github.com/voice-social/voice-buildkite-template.git

steps:
# helm deploy to prod
  - label: ":helm: Trigger Helm Deploy"
    command:
      - "buildkite-agent pipeline upload voice-buildkite-template/helm/deploy/template.yaml"
    env:
      HELM_RELEASE: voice-eos-hyperion
      HELM_RELEASE_NAMESPACE: prod
      HELM_RELEASE_TAG: ${BUILDKITE_COMMIT}
      HELM_VALUE_FILE: helm/values/prod.yaml
      BUILDKITE_AGENT: voice-main-prod-deployer
      NR_DEPLOY_MARKER: skip
    concurrency: 1
    concurrency_group: "${BUILDKITE_PIPELINE_SLUG}/prod"
    agents: *default-agents
    plugins: *default-plugins
