tag: v3.3.5
config:
  serverName: "explorer.voice.com"
  provider_url: https://voice.com
  provider_name: "voice"
  ## this only take the image form URL
  chain_logo_url: "https://storage.googleapis.com/voice_logo/logo.ico"
  es_replicas: 1 

services:
  voice-eos-hyperion:
    customLabels:
      app: "voice-eos-hyperion-api"
      app.kubernetes.io/instance: "voice-eos-hyperion-api"
    customSelectors: 
      app: "voice-eos-hyperion-api"
    type: NodePort
    ports:
      - port: 7000
        targetPort: 7000
        protocol: TCP
        name: hyperion-api
        nodePort: 30036

  voice-hyperion-rabbit-mq:
    customLabels:
      # serviceMonitors: "voice-hyperion-rabbit-mq"
      app.kubernetes.io/name: voice
      app.kubernetes.io/instance: "voice-hyperion-rabbit-mq"
      app.kubernetes.io/branch: "master"
      app.kubernetes.io/authority: "voice-eos-hyperion"
      app.kubernetes.io/component: "voice-hyperion-rabbit-mq"
    type: ClusterIP
    customSelectors: 
      service: "voice-hyperion-rabbit-mq"
    ports:
      - port: 5672
        targetPort: 5672
        protocol: TCP
        name: rabbitmq-port
      - port: 15672
        targetPort: 15672
        protocol: TCP
        name: rabbitmq-management-port
      - port: 15692
        targetPort: 15692
        protocol: TCP
        name: monitoring


statefulsets:
  voice-hyperion-rabbit-mq:
    serviceName: rabbit-mq-headless
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cat
              operator: In
              values:
              - data
    customLabels:
      service: "voice-hyperion-rabbit-mq"
      app.kubernetes.io/name: voice
      app.kubernetes.io/instance: "voice-hyperion-rabbit-mq"
      app.kubernetes.io/branch: "master"
      app.kubernetes.io/authority: "voice-eos-hyperion"
      app.kubernetes.io/component: "voice-hyperion-rabbit-mq"
    replicaCount: 1
    customSelectors:
      service: voice-hyperion-rabbit-mq
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        partition: 0
    volumeClaimTemplates:
      - metadata:
          name: rabbit-mq-data
          labels:
            app.kubernetes.io/name: voice
            app.kubernetes.io/instance: "voice-hyperion-rabbit-mq"
            app.kubernetes.io/branch: "master"
            app.kubernetes.io/authority: "voice-eos-hyperion"
            app.kubernetes.io/component: "voice-eos-hyperion"
            app.kubernetes.io/chain: "voice-hyperion-rabbit-mq"
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
    containers:
      voice-hyperion-rabbit-mq:
        image:  rabbitmq:3.9.11-management-alpine
        imagePullPolicy: IfNotPresent
        extraVars:
          RABBITMQ_DEFAULT_VHOST: voice
          RABBITMQ_DEFAULT_USER: voice
          RABBITMQ_DEFAULT_PASS: voice

deployments:
  voice-eos-hyperion-indexer:
    replicaCount: 1
    terminationGracePeriodSeconds: 60
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cat
              operator: In
              values:
              - hyperion-indexer
    volumes: 
    - name: eos-hyperion-indexer-config
      configMap:
        name:  eos-hyperion-indexer-config
    - name: eos-hyperion-connections
      configMap:
        name:  eos-hyperion-connections
    initContainers:
      check-hyperion-rabbit-mq-health:
        extraVars:
          user: voice
          pass: voice
          vhost: voice
        image: "gcr.io/voice-prod-infra-services/auto-init-container/auto-init-container:latest"
        imagePullPolicy: Always
        command: ['bash','check-rabbit-mq-health.sh','voice-hyperion-rabbit-mq.{{ .Release.Namespace }}.svc.cluster.local']
    lifecycle:
          prestop:
            exec:
              command: ["bash","stop.sh",voice-indexer""]
    containers:
      voice-eos-hyperion-indexer:
        containerPorts:
          - containerPort: 7000
            protocol: TCP
            name: hyperion-api
        image: "gcr.io/voice-prod-infra-services/voice/voice-eos-hyperion:{{ .Values.tag }}"
        imagePullPolicy: Always
        command: ["bash", "run.sh","voice-indexer"]
        extraVars:
          http_proxy: http://proxy.service:3128
          https_proxy: http://proxy.service:3128
          no_proxy: .svc.cluster.local,.service,.internal,.vops.int,metadata.google.internal
        resources:
          requests:
            cpu: "1500m"
            memory: "1024Mi"
        volumeMounts:
          - name: eos-hyperion-connections
            mountPath: /hyperion-history-api/connections.json
            subPath: connections.json
          - name: eos-hyperion-indexer-config
            mountPath: hyperion-history-api/chains/voice.config.json
            subPath: voice.config.json
  
  voice-eos-hyperion-api:
    replicaCount: 1
    terminationGracePeriodSeconds: 60
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cat
              operator: In
              values:
              - api
    volumes: 
    - name: eos-hyperion-api-config
      configMap:
        name: eos-hyperion-api-config
    - name: eos-hyperion-connections
      configMap:
        name:  eos-hyperion-connections        
    initContainers:
      check-hyperion-rabbit-mq-health:
        extraVars:
          user: voice
          pass: voice
          vhost: voice
        image: "gcr.io/voice-prod-infra-services/auto-init-container/auto-init-container:latest"
        imagePullPolicy: Always
        command: ['bash','check-rabbit-mq-health.sh','voice-hyperion-rabbit-mq.{{ .Release.Namespace }}.svc.cluster.local']
    containers:
      voice-eos-hyperion-api:
        livenessProbe:
          httpGet:
            path: /v2/health
            port: 7000
          periodSeconds: 10
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/health
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 10
        containerPorts:
          - containerPort: 7000
            protocol: TCP
            name: hyperion-api
        image: "gcr.io/voice-prod-infra-services/voice/voice-eos-hyperion:{{ .Values.tag }}"
        imagePullPolicy: Always
        command: ["bash", "run.sh","voice-api"]
        extraVars:
          http_proxy: http://proxy.service:3128
          https_proxy: http://proxy.service:3128
          no_proxy: .svc.cluster.local,.service,.internal,.vops.int,metadata.google.internal
        lifecycle:
          prestop:
            exec:
              command: ["bash","stop.sh",voice-api""]
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
          - name: eos-hyperion-connections
            mountPath: hyperion-history-api/connections.json
            subPath: connections.json
            readOnly: false
          - name: eos-hyperion-api-config
            mountPath: hyperion-history-api/chains/voice.config.json
            subPath: voice.config.json
            readOnly: false
hpas:
  voice-eos-hyperion-api:
    minReplicas: 1 
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
configmaps:
  config:
    eos-hyperion-indexer-config:
## turn the abi true only on the 1st run or if the elastic data has been wiped 
      abi_scan: true
      indexer: true
      api: false
    eos-hyperion-api-config:
      indexer: false
      api: true
  connections:
    eos-hyperion-connections:
      elasticsearch:
        host: elastic.service
        ingest_nodes: elastic.service
        user: ""
        pass: ""     
      redis:
        host: "172.31.40.4"
        port: "6379"
      chains:
        name: "voice production chain"
        chain_id: "8fb2215338190e08e3ec6c2b012d5d2a4adc2bbce11c9e8746ddfe7dec199fe5"
        http: "http://chain-api-lb-prod.service.b-oma-prod.vops.int:8888"
        ship: "ws://ship-lb-prod.service.b-oma-prod.vops.int:8080"
        WS_ROUTER_PORT: 7001
        WS_ROUTER_HOST: "127.0.0.1"
      amqp: 
        service: voice-hyperion-rabbit-mq
        user: "voice"
        pass: "voice"
        vhost: "voice"