{{- if .Values.secrets }}
{{- $root := . }}
{{- range $name, $secret := .Values.secrets }}
{{- if not $secret.disabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
{{- if $secret.customLabels }}
{{ toYaml $secret.customLabels | indent 4}}
{{- else }}
{{ include "voice-chart.labels" $root | indent 4 }}
{{- end }}
type: Opaque
{{- if $secret.data }}
data:
{{ toYaml $secret.data | indent 2 }}
{{- end }}
{{- if $secret.stringData }}
stringData:
{{ toYaml $secret.stringData | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
